---
- name: Converge
  hosts: all
  any_errors_fatal: true
  vars:
    vault_backend: file
    vault_cluster_disable: true
    vault_address: "0.0.0.0"
    unseal_keys_dir_output: "{{ playbook_dir }}/unsealKeys"
    root_token_dir_output: "{{ playbook_dir }}/rootToken"

  roles:
    - role: vault
