---
- name: deploy Vault
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    vault_backend: file
    vault_cluster_disable: True
    vault_log_level: debug
    vault_address: "0.0.0.0"
    vault_enable_logrotate: True

  pre_tasks:
    - ec2_metadata_facts:

  roles:
    - vault
#    - ansible-node-exporter