---
galaxy_info:
  author: Artsiom Azarenka
  description: HashiCorp Vault Role
  license: BSD
  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 6
        - 7

  galaxy_tags:
    - networking
    - security
    - system

dependencies: []
